apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
        matchLabels:
          app: react-app-deployment
  replicas: 2
  template:
        metadata:
          labels:
                app: react-app-deployment
        spec:
          containers:
          - name: react-app-deployment
            image: phx.ocir.io/oraclemetodista/reactshort-repo/react-app:version1.0
            imagePullPolicy: Always
            ports:
            - containerPort: 3000
          imagePullSecrets:
          - name: ocirsecret
---
apiVersion: v1
kind: Service   
metadata:
  name: react-server
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
        app: react-app-deployment